name: main

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install poetry
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv for discord_bot_eternal_dice
        id: cached-discord-bot-eternal-dice-poetry
        uses: actions/cache@v2
        with:
          path: |
            discord_bot_eternal_dice/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('discord_bot_eternal_dice/poetry.lock') }}

      - name: Poetry install for discord_bot_eternal_dice/
        run: cd discord_bot_eternal_dice && poetry install
        if: steps.cached-discord-bot-eternal-dice-poetry.outputs.cache-hit != 'true'

      - name: Load cached venv for infra
        id: cached-infra-poetry
        uses: actions/cache@v2
        with:
          path: infra/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('infra/poetry.lock') }}

      - name: Poetry install for infra/
        run: cd infra && poetry install
        if: steps.cached-infra-poetry.outputs.cache-hit != 'true'

      - name: Code Quality
        run: make quality

      - name: Pytest
        run: cd discord_bot_eternal_dice && poetry run pytest --cov=discord_bot_eternal_dice --cov-report=xml

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install poetry
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv for discord_bot_eternal_dice
        id: cached-discord-bot-eternal-dice-poetry
        uses: actions/cache@v2
        with:
          path: |
            discord_bot_eternal_dice/.venv
            discord_bot_eternal_dice/.serverless/cache
          key: venv-${{ runner.os }}-${{ hashFiles('discord_bot_eternal_dice/poetry.lock') }}

      - name: Poetry install for discord_bot_eternal_dice/
        run: cd discord_bot_eternal_dice && poetry install
        if: steps.cached-discord-bot-eternal-dice-poetry.outputs.cache-hit != 'true'

      - name: Load cached node modules
        id: cached-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Npm install
        run: npm install
        if: steps.cached-node-modules.outputs.cache-hit != 'true'

      - name: Package the bot
        run: cd discord_bot_eternal_dice && npx serverless package

      - name: Package the error handler
        run: cd error_handler && npx serverless package

      - name: Create artifact for discord_bot_eternal_dice
        uses: actions/upload-artifact@v2
        with:
          name: discord_bot_eternal_dice_package
          path: discord_bot_eternal_dice/.serverless/discord-bot-eternal-dice.zip

      - name: Create artifact for the error_handler
        uses: actions/upload-artifact@v2
        with:
          name: error_handler_package
          path: error_handler/.serverless/error-handler.zip

      - name: Create artifact for the infra module
        uses: actions/upload-artifact@v2
        with:
          name: infra
          path: infra/

  deploy:
    needs:
      - test
      - build
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3

      - name: Restore the artifact for the discord-app
        uses: actions/download-artifact@v3
        with:
          name: discord_bot_eternal_dice_package
          path: discord_bot_eternal_dice/.serverless/

      - name: Restore the artifact for the error_handler
        uses: actions/download-artifact@v3
        with:
          name: error_handler_package
          path: error_handler/.serverless/

      - name: Install Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install poetry
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv for infra
        id: cached-infra-poetry
        uses: actions/cache@v2
        with:
          path: infra/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('infra/poetry.lock') }}

      - name: Poetry install for infra/
        run: cd infra && poetry install
        if: steps.cached-infra-poetry.outputs.cache-hit != 'true'

      - name: Synthesize CDK
        run: cd infra && poetry run npx cdk synth --output build/cdk.out
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_TARGET_ACCOUNT: ${{ secrets.AWS_TARGET_ACCOUNT }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}

      - name: Deploy CDK
        run: cd infra && poetry run npx cdk deploy --app ./build/cdk.out --require-approval never
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_TARGET_ACCOUNT: ${{ secrets.AWS_TARGET_ACCOUNT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install poetry
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Build Changelog
        id: changes
        run: echo "::set-output name=changelog::$(git log --format=%B -1)"

      - name: Get the base version
        id: release_version
        run: echo "::set-output name=version::$(cd discord_app && poetry version -s)"

      - name: Get the date of the release
        id: release_date
        run: echo "::set-output name=date::$(date +"%Y-%m-%d")"

      - name: Get the shorthash of the commit
        id: release_hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Check changelog
        run: echo ${{ steps.changes.outputs.changelog }}

      - name: Check release name
        run: echo "v${{ steps.release_version.outputs.version }}.${{ steps.release_date.outputs.date }}.${{ steps.release_hash.outputs.sha_short }}"

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ steps.release_version.outputs.version }}.${{ steps.release_date.outputs.date }}.${{ steps.release_hash.outputs.sha_short }}"
          release_name: "v${{ steps.release_version.outputs.version }}.${{ steps.release_date.outputs.date }}.${{ steps.release_hash.outputs.sha_short }}"
          body: ${{ steps.changes.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
